#!/usr/bin/env fish

#
# Go to the root of the repo.
#
cd (git rev-parse --show-toplevel)

#
# Update version in package.json.
#
set v (scripts/updateVersion)

#
# And commit.
#
git add package.json
git commit -m "'Update version: $v'"

#
# Push the commits and the tag.
#
git tag $v
git push origin tag
git push origin HEAD

#
# ###
#
npm publish
